### ISSUE TITLE
build subcommand

### ISSUE THREAD

**Issue by zaucy** [ecsact-dev/ecsact_cli#12]
A general utility to replace [ecsact_rtb](https://github.com/ecsact-dev/ecsact_rtb). Instead of relying on ecsact_rtb to compile specifically the ecsact_rt_entt runtime a general utility that takes in 'recipies' (naming wip) which dictates how a runtime is compiled.

This will be necessary since there will be multiple implementations of the Ecsact Runtime. We already plan on creating a runtime with flecs, bevvy, and at Seaube we have an internal one for our Ecsact Cloud async implementation.

Command may look something like this:

```
ecsact build file1.ecsact file2.ecsact --recipe=entt --output=ecsact_runtime.dll
```

`--recipe` (or `-r`) will take in a 'built-in' recipe config name (similar to how `ecsact codegen` plugins work) that will be looked up in the shared directory:
```
{ECSACT_SDK_INSTALL_DIR}/share/ecsact/recipes/ecsact_build_{NAME}_recipe.yml
```

If a built-in one doesn't exist it will be treated as a path. Multiple recipes may be specified resulting in a an output that's built from multiple recipes. Some validation must be done to make sure there are no clashing implementations such as 2 recipes implementing the same method.

The recipe format will likely be a YAML file. Not for any other reason than I like YAML files. If there's a convincing enough reason to have some other format I will consider it.

Here's an example of what I'm thinking:

```yaml
name: EnTT

# The runtime configuration this recipe builds
config:
  exports:
    - ecsact_execute_systems
    # ... etc.
  imports:
    # methods this recipe uses, but does not implement. Another recipe must export these methods or the build will fail

# Ecsact codegen that needs to run. Specify plugins and output directories.
codegen:
  - output: include # Relative paths only. Codegen is executed in special temporary directory for build
    plugins:
     - cpp_header
     - cpp_meta_header

# Source files required to build runtime. May be fetched from external source such as a github repo
source: # WIP. Not sure whats the best way to organize these files
 - name: entt_repository
   fetch: https://github.com/skypjack/entt/archive/refs/tags/v3.11.1.zip
   sha256: SHA256-for-security-purposes
 - name: ecsact_rt_entt_repository
   fetch: https://github.com/ecsact-dev/ecsact_rt_entt/archive/refs/tags/0.1.0.zip
   sha256: SHA256-for-security-purposes

# The actual build instructions!
build:
  - platform: # instructions only for the windows platform
      os: windows
      arch: x64
    output_extension: .dll
    toolchain: msvc
    defines: # defines passed to msvc cl.exe with /D
     - ECSACT_ENTT_RUNTIME_PACKAGE=::{MAIN_PACKAGE}::package
    # TODO... this part needs more thought
```

I'd like to add other options such as 'optimized' vs 'debug' or possibly custom configuration options for each recipe. For the first release of the build command I would like to just cover what ecsact_rtb does and nothing more.
